version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      # 日本標準時 (UTC +09:00) を使用する
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - naa0yama
    assignees:
      - naa0yama

    # GitHub アクションの依存関係を維持する
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      # 日本標準時 (UTC +09:00) を使用する
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - naa0yama
    assignees:
      - naa0yama
