---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# files: "^subdir/"
default_install_hook_types:
  - "pre-commit"
  - "pre-push"
minimum_pre_commit_version: 2.21.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: fix-byte-order-marker
      - id: check-json
        exclude: |
          (?x)^(
              .devcontainer/devcontainer.json|
              .vscode/extensions.json|
              .vscode/settings.json
          )$
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ["-c=.yamllint.yml"]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
        entry: /bin/sh -c "cd . && poetry check --no-interaction"
        files: ^pyproject.toml$
      - id: poetry-lock
        entry: /bin/sh -c "cd . && poetry lock --no-interaction --no-update"
        files: ^pyproject.toml$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--settings-file", "pyproject.toml"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: "run mypy in the .venv of your local project"
        entry: /bin/sh -c "cd . && .venv/bin/mypy --config-file pyproject.toml src tests"
        language: python
        types_or: [python, pyi]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
        verbose: true

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        entry: "/bin/sh -c 'cd . && blacken-docs'"

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - flake8-annotations
          - flake8-black
          - flake8-bugbear
          - flake8-builtins
          - flake8-commas
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-fixme
          - flake8-isort
          - flake8-print
          - flake8-return
          - flake8-simplify
          - flake8-unused-globals
          - flake8-variables-names
          - pyproject-flake8
        args: ["--config", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: /bin/sh -c "cd . && .venv/bin/pytest"
        args: ["-c", "pyproject.toml"]
        stages:
          - "push"
        language: system
        pass_filenames: false
        always_run: true
