---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#files: "^subdir/"
minimum_pre_commit_version: 2.21.0

repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]
        verbose: true

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        entry: /bin/sh -c "cd . && blacken-docs"

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.0
    hooks:
      - id: isort
        args: ["--settings-file", "pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config", "setup.cfg"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: ["-c=.yamllint.yml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: fix-byte-order-marker
      - id: check-json
        exclude: |
          (?x)^(
              .devcontainer/devcontainer.json|
              .vscode/extensions.json|
              .vscode/settings.json
          )$
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
