---
# https://yamllint.readthedocs.io/en/stable/configuration.html
# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default

rules:
  comments:
    min-spaces-from-content: 1
    level: warning
  empty-values: enable
  indentation:
    level: error
    indent-sequences: consistent
  line-length:
    max: 99
