[env]
# gh-sync:keep-start
# Project-specific dependencies are listed here.

# gh-sync:keep-end

[tools]
"aqua:cli/cli" = "2.98.0"
"github:naa0yama/graft" = "0.5.11"
actionlint = "1.7.12"
dprint = "0.56.1"
ghalint = "1.5.6"
tmux = "3.6a"
usage = "3.6.0"
uv = "latest"
zizmor = "1.29.0"

[task_config]
includes = [
	".mise/tasks.toml",
	".mise/overrides.toml",
]
