[tool.poetry]
name                       = "pythonboilerplate"
version                    = "0.1.0"
description                = "Python を開発する時用ボイラープレート"
authors                    = [
    "Naoki Aoyama"
]
license                    = "AGPL-3.0"

[tool.poetry.dependencies]
python                     = "~3.8"

[tool.poetry.dev-dependencies]
autoflake                  = "~1.7"
black                      = "~22.10.0"
flake8                     = "~5.0.0"
flake8-annotations         = "~2.9.0"
flake8-black               = "~0.3.2"
flake8-bugbear             = "~22.9.0"
flake8-builtins            = "~1.5.3"
flake8-commas              = "~2.1.0"
flake8-comprehensions      = "~3.10.0"
flake8-debugger            = "~4.1.0"
flake8-docstrings          = "~1.6.0"
flake8-fixme               = "~1.1.1"
flake8-isort               = "~4.2.0"
flake8-print               = "~5.0.0"
flake8-return              = "~1.1.2"
flake8-simplify            = "~0.19.2"
flake8-variables-names     = "~0.0.4"
ipykernel                  = "~6.16.0"
isort                      = "~5.10.0"
mypy                       = "~0.982"
pip                        = "^22.0.0"
pytest                     = "~7.1.0"
pytest-cov                 = "~3.0.0"
tox                        = "~3.26.0"

[tool.black]
line-length                = 99
exclude                    = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
)
'''

[tool.coverage]
[tool.coverage.run]
branch                     = true
command_line               = "-m pytest"

[tool.isort]
include_trailing_comma     = true
line_length                = 99
force_single_line          = true
force_sort_within_sections = true

[tool.pytest]
[tool.pytest.ini_options]
minversion                 = "6.0"
addopts                    = [
    "-r sfp",
    "--verbose",
    "--verbose",
    "--durations=0",
    "--cov=src",
    "--cov=tests",
    "--cov-report=term",
    "--cov-report=term-missing",
    "--cov-report=term-missing",
    "--cov-report=xml"
]

[build-system]
requires                   = [
    "poetry-core>=1.0.0",
    "setuptools",
]
build-backend              = "poetry.core.masonry.api"
