# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Prebuild DevContainer"
description: "Build and push devcontainer image to GitHub Container Registry"
inputs:
  github_token:
    description: "GitHub token for registry authentication"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Convert repository owner/repo to lowercase
      id: repo_name
      shell: bash
      run: echo "lowercase=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Pre-build dev container image
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
      with:
        imageName: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
        cacheFrom: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
        refFilterForPush: refs/heads/main
        noCache: false
