name: push workflow
on: [push]
jobs:
  run:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
          - 3.8
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python
        id: python_cache_id
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.pythonLocation }}
            ${{ github.workspace }}/.tox
          key: python-${{ env.pythonLocation }}-v${{ matrix.python-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/tox.ini')) }}-${{ hashFiles(format('{0}{1}', github.workspace, '/setup.cfg')) }}-${{ hashFiles(format('{0}{1}', github.workspace, '/pyproject.toml')) }}

      - name: Install dependencies
        if: steps.python_cache_id.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: pytest
          env_vars: OS,PYTHON
          fail_ci_if_error: true
